"use strict";
require("dotenv").config();
const path=require("path");const express=require("express");const cors=require("cors");const {Client,GatewayIntentBits}=require("discord.js");
const token=process.env.DISCORD_BOT_TOKEN,guildId=process.env.DISCORD_GUILD_ID,port=Number(process.env.PORT||3000);
if(!token||!guildId){console.error("Missing DISCORD_BOT_TOKEN or DISCORD_GUILD_ID in environment variables.");process.exit(1)}
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildVoiceStates]});
const app=express();app.use(cors());app.use(express.json({limit:"20kb"}));app.use(express.static(path.join(__dirname,"public")));
const directoryRoleIds=new Set(["1530712642384040027","1521187079336362024","1531109479264026706","1548732297669255259","1548732341185155103","1548732606508703744"]);
const strong=new Set(["Administrator","ManageGuild","ManageRoles","ManageChannels","ManageMessages","ManageWebhooks","ManageNicknames","BanMembers","KickMembers","ModerateMembers","MentionEveryone","ViewAuditLog","ManageEvents","ManageThreads","ManageEmojisAndStickers"]);const activity=new Map(),voiceSessions=new Map(),sendHits=new Map();
const stat=id=>{if(!activity.has(id))activity.set(id,{messages:0,mentionsReceived:0,mentionsSent:0,voiceMinutes:0,voiceJoins:0,chatRounds:0});return activity.get(id)};const guild=()=>client.guilds.fetch(guildId);const directory=r=>directoryRoleIds.has(r.id);const important=p=>p.toArray().filter(x=>strong.has(x));
function role(r){return{id:r.id,name:r.name,color:r.hexColor,position:r.position,permissions:important(r.permissions),membersCount:r.members?.size||0}}
function roles(m){return m.roles.cache.filter(r=>r.id!==m.guild.id).sort((a,b)=>b.position-a.position).map(role)}function leadership(m){return m.roles.cache.filter(r=>r.id!==m.guild.id&&directory(r)).sort((a,b)=>b.position-a.position).map(role)}
function member(m){const rs=roles(m),ls=leadership(m);return{id:m.id,name:m.displayName,username:m.user.username,globalName:m.user.globalName,avatar:m.user.displayAvatarURL({extension:"png",size:256}),roles:rs,importantRoles:ls,rank:ls[0]?.name||rs[0]?.name||"عضو",stats:stat(m.id)}}
async function members(g){await g.members.fetch();return[...g.members.cache.values()].filter(m=>!m.user.bot)}function sorted(ms){return ms.sort((a,b)=>(stat(b.id).messages+stat(b.id).voiceMinutes)-(stat(a.id).messages+stat(a.id).voiceMinutes)).map(member)}
app.get("/health",(q,r)=>r.json({ok:true,botReady:client.isReady()}));
app.get("/api/public/server",async(q,r)=>{try{const g=await guild();r.json({id:g.id,name:g.name,icon:g.iconURL({extension:"png",size:256}),memberCount:g.memberCount,ownerName:"فهد المطيري",invite:process.env.DISCORD_INVITE_URL||""})}catch(e){r.status(503).json({error:"Discord server is unavailable"})}});
app.get("/api/public/roles",async(q,r)=>{try{const g=await guild();r.json({roles:g.roles.cache.filter(x=>x.id!==g.id&&directory(x)).sort((a,b)=>b.position-a.position).map(role)})}catch(e){r.status(503).json({error:"Roles unavailable"})}});
app.get("/api/public/roles/:id/members",async(q,r)=>{try{const g=await guild(),ro=g.roles.cache.get(q.params.id);if(!ro||!directory(ro))return r.status(404).json({error:"Role not found"});r.json({role:role(ro),members:(await members(g)).filter(m=>m.roles.cache.has(ro.id)).map(member)})}catch(e){r.status(503).json({error:"Role members unavailable"})}});
app.get("/api/public/members",async(q,r)=>{try{const term=String(q.query.q||"").trim().toLowerCase();if(!term)return r.json({members:[]});const ms=await members(await guild());r.json({members:ms.filter(m=>`${m.displayName} ${m.user.username} ${m.user.globalName||""}`.toLowerCase().includes(term)).slice(0,25).map(member)})}catch(e){r.status(503).json({error:"Members unavailable"})}});
app.get("/api/public/top",async(q,r)=>{try{const ms=(await members(await guild())).map(member);const by=k=>[...ms].sort((a,b)=>(b.stats[k]||0)-(a.stats[k]||0)).slice(0,10);r.json({messages:by("messages"),mentions:by("mentionsReceived"),voice:by("voiceMinutes"),joins:by("voiceJoins")})}catch(e){r.status(503).json({error:"Top unavailable"})}});
app.get("/api/public/member/:id",async(q,r)=>{try{const g=await guild(),m=await g.members.fetch(q.params.id).catch(()=>null);if(!m||m.user.bot)return r.status(404).json({error:"Member not found"});const high=m.roles.cache.filter(x=>x.id!==g.id&&!x.managed).sort((a,b)=>b.position-a.position).first();const upcoming=g.roles.cache.filter(x=>x.position>(high?.position||0)&&!x.managed).sort((a,b)=>a.position-b.position).first(8).map(role);r.json({...member(m),highestRole:high?role(high):null,permissions:high?important(high.permissions):[],upcomingRoles:upcoming})}catch(e){r.status(404).json({error:"Member not found"})}});
app.post("/api/public/message",async(q,r)=>{const now=Date.now(),ip=q.ip||"unknown",last=sendHits.get(ip)||0;if(now-last<30000)return r.status(429).json({error:"انتظر 30 ثانية قبل الإرسال مرة أخرى"});const text=String(q.body?.message||"").trim(),target=String(q.body?.memberId||"").trim();if(!text||text.length>1000||!target)return r.status(400).json({error:"بيانات الرسالة غير صحيحة"});try{const g=await guild(),m=await g.members.fetch(target).catch(()=>null);if(!m||m.user.bot)return r.status(404).json({error:"العضو غير موجود"});if(!process.env.MESSAGE_SEND_KEY)return r.status(503).json({error:"ميزة الإرسال غير مفعلة"});if(String(q.body.key||"")!==process.env.MESSAGE_SEND_KEY)return r.status(403).json({error:"غير مصرح"});await m.send(text);sendHits.set(ip,now);r.json({ok:true})}catch(e){r.status(500).json({error:"تعذر إرسال الرسالة"})}});
client.on("messageCreate",m=>{if(m.author.bot)return;const s=stat(m.author.id);s.messages++;s.chatRounds++;for(const id of m.mentions.users.keys()){stat(id).mentionsReceived++;s.mentionsSent++}});client.on("voiceStateUpdate",(o,n)=>{const id=n.id;if(!o.channelId&&n.channelId){voiceSessions.set(id,Date.now());stat(id).voiceJoins++}if(o.channelId&&!n.channelId&&voiceSessions.has(id)){stat(id).voiceMinutes+=Math.round((Date.now()-voiceSessions.get(id))/60000);voiceSessions.delete(id)}});
app.get("*",(q,r)=>r.sendFile(path.join(__dirname,"public","index.html")));app.listen(port,()=>console.log(`MLD listening on ${port}`));client.once("ready",()=>console.log(`Discord bot logged in as ${client.user.tag}`));client.login(token).catch(e=>{console.error("Discord login failed:",e.message);process.exit(1)});
