"use strict";
require("dotenv").config();
const path=require("path"),express=require("express"),cors=require("cors");
const {Client,GatewayIntentBits,EmbedBuilder}=require("discord.js");
const token=process.env.DISCORD_BOT_TOKEN,guildId=process.env.DISCORD_GUILD_ID,port=Number(process.env.PORT||3000);
if(!token||!guildId){console.error("Missing DISCORD_BOT_TOKEN or DISCORD_GUILD_ID");process.exit(1)}
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildVoiceStates]});
const app=express();app.disable("x-powered-by");app.use(cors());app.use(express.json({limit:"20kb"}));app.use(express.static(path.join(__dirname,"public")));
const roleIds=["1530712642384040027","1521187079336362024","1531109479264026706","1548732297669255259","1548732341185155103","1548732606508703744"],roleSet=new Set(roleIds);
const important=new Set(["Administrator","ManageGuild","ManageRoles","ManageChannels","ManageMessages","ManageWebhooks","ManageNicknames","BanMembers","KickMembers","ModerateMembers","MentionEveryone","ViewAuditLog","ManageEvents","ManageThreads","ManageEmojisAndStickers"]);
const activity=new Map(),voiceSessions=new Map(),sendHits=new Map();let guildCache=null,cacheAt=0,refreshing=null;
const stats=id=>{if(!activity.has(id))activity.set(id,{messages:0,mentionsReceived:0,mentionsSent:0,voiceMinutes:0,voiceJoins:0,chatRounds:0});return activity.get(id)};
async function getGuild(){if(guildCache&&Date.now()-cacheAt<15000)return guildCache;if(refreshing)return refreshing;refreshing=client.guilds.fetch(guildId).then(g=>{guildCache=g;cacheAt=Date.now();refreshing=null;return g}).catch(e=>{refreshing=null;throw e});return refreshing}
async function getMembers(g){await g.members.fetch();return [...g.members.cache.values()].filter(m=>!m.user.bot)}
const isDir=r=>roleSet.has(r.id), perms=p=>p.toArray().filter(x=>important.has(x));
function roleJson(r,count=r.members?.size||0){return{id:r.id,name:r.name,color:r.hexColor,position:r.position,permissions:perms(r.permissions),membersCount:count,mentionable:r.mentionable}}
function memberJson(m){const rs=m.roles.cache.filter(r=>r.id!==m.guild.id).sort((a,b)=>b.position-a.position).map(r=>roleJson(r));const ls=rs.filter(r=>roleSet.has(r.id));return{id:m.id,name:m.displayName,username:m.user.username,globalName:m.user.globalName,avatar:m.user.displayAvatarURL({extension:"png",size:256}),joinedAt:m.joinedAt,roles:rs,importantRoles:ls,rank:ls[0]?.name||rs[0]?.name||"عضو",stats:stats(m.id)}}
app.get("/health",(q,r)=>r.json({ok:true,botReady:client.isReady()}));
app.get("/api/public/server",async(q,r)=>{try{const g=await getGuild();r.json({id:g.id,name:g.name,icon:g.iconURL({extension:"png",size:256}),memberCount:g.memberCount,ownerName:process.env.SERVER_FOUNDER_NAME||"فهد المطيري",invite:process.env.DISCORD_INVITE_URL||""})}catch(e){r.status(503).json({error:"Discord server unavailable"})}});
app.get("/api/public/roles",async(q,r)=>{try{const g=await getGuild(),ms=await getMembers(g);r.json({roles:roleIds.map(id=>g.roles.cache.get(id)).filter(Boolean).map(x=>roleJson(x,ms.filter(m=>m.roles.cache.has(x.id)).length))})}catch(e){console.error(e);r.status(503).json({error:"Roles unavailable"})}});
app.get("/api/public/roles/:id/members",async(q,r)=>{try{const g=await getGuild(),role=g.roles.cache.get(q.params.id);if(!role||!isDir(role))return r.status(404).json({error:"Role not found"});const ms=(await getMembers(g)).filter(m=>m.roles.cache.has(role.id));r.json({role:roleJson(role,ms.length),members:ms.map(memberJson)})}catch(e){r.status(503).json({error:"Role members unavailable"})}});
app.get("/api/public/members",async(q,r)=>{try{const term=String(q.query.q||"").trim().toLocaleLowerCase("ar"),ms=await getMembers(await getGuild());const out=term?ms.filter(m=>`${m.displayName} ${m.user.username} ${m.user.globalName||""}`.toLocaleLowerCase("ar").includes(term.replace(/^@/,""))):ms;r.json({members:out.map(memberJson)})}catch(e){r.status(503).json({error:"Members unavailable"})}});
app.get("/api/public/top",async(q,r)=>{try{const ms=(await getMembers(await getGuild())).map(memberJson),by=k=>[...ms].sort((a,b)=>(b.stats[k]||0)-(a.stats[k]||0)).slice(0,10);r.json({messages:by("messages"),mentions:by("mentionsReceived"),voice:by("voiceMinutes"),joins:by("voiceJoins")})}catch(e){r.status(503).json({error:"Top unavailable"})}});
app.get("/api/public/member/:id",async(q,r)=>{try{const g=await getGuild(),m=await g.members.fetch(q.params.id).catch(()=>null);if(!m||m.user.bot)return r.status(404).json({error:"Member not found"});const high=m.roles.cache.filter(x=>x.id!==g.id&&!x.managed).sort((a,b)=>b.position-a.position).first();r.json({...memberJson(m),highestRole:high?roleJson(high):null,permissions:high?perms(high.permissions):[],upcomingRoles:g.roles.cache.filter(x=>x.position>(high?.position||0)&&!x.managed).sort((a,b)=>a.position-b.position).first(8).map(x=>roleJson(x))})}catch(e){r.status(404).json({error:"Member not found"})}});
app.post("/api/public/message",async(q,r)=>{const ip=q.ip||"unknown",now=Date.now(),last=sendHits.get(ip)||0;if(now-last<10000)return r.status(429).json({error:"انتظر 10 ثواني قبل الإرسال مرة أخرى"});const title=String(q.body?.title||"رسالة من إدارة MLD").trim(),text=String(q.body?.message||"").trim(),id=String(q.body?.memberId||"").trim();if(!id||!text||text.length>2000||title.length>120)return r.status(400).json({error:"بيانات الرسالة غير صحيحة"});try{const m=await (await getGuild()).members.fetch(id).catch(()=>null);if(!m||m.user.bot)return r.status(404).json({error:"العضو غير موجود"});await m.send({embeds:[new EmbedBuilder().setTitle(title).setDescription(text).setColor("#ff9cdc").setFooter({text:"MLD Community"}).setTimestamp()]});sendHits.set(ip,now);r.json({ok:true})}catch(e){console.error(e);r.status(500).json({error:"تعذر الإرسال؛ قد يكون الخاص مقفلًا"})}});
client.on("messageCreate",m=>{if(m.author.bot)return;const s=stats(m.author.id);s.messages++;s.chatRounds++;for(const id of m.mentions.users.keys()){stats(id).mentionsReceived++;s.mentionsSent++}});
client.on("voiceStateUpdate",(o,n)=>{const id=n.id;if(!o.channelId&&n.channelId){voiceSessions.set(id,Date.now());stats(id).voiceJoins++}if(o.channelId&&!n.channelId&&voiceSessions.has(id)){stats(id).voiceMinutes+=Math.round((Date.now()-voiceSessions.get(id))/60000);voiceSessions.delete(id)}});
app.get("*",(q,r)=>r.sendFile(path.join(__dirname,"public","index.html")));app.listen(port,()=>console.log(`MLD listening on ${port}`));client.once("ready",()=>console.log(`Logged in as ${client.user.tag}`));client.login(token).catch(e=>{console.error(e.message);process.exit(1)});
